User.validatesPresenceOf('email', 'username', 'password', 'secret_code')
User.validatesLengthOf('username', {min:3, max:20})
User.validatesLengthOf('password', {min:8})
User.validatesFormatOf('email', {with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i})
User.validatesFormatOf('secret_code', {with: /^d2CUtD7cWdSBspTS$/i})
User.validatesUniquenessOf('email', 'username')
